quarkus.banner.enabled=true
quarkus.banner.path=banner.txt
ec2pf.watch.max-backoff-secs=60
ec2pf.watch.default-interval-secs=30
ec2pf.watch.min-interval-secs=5
ec2pf.watch.port-release-attempts=10
ec2pf.watch.port-release-interval-ms=500
ec2pf.session.startup-attempts=10
ec2pf.session.startup-check-interval-ms=1000
ec2pf.session.cli-timeout-secs=30
ec2pf.pid.directory=${user.dir}
quarkus.log.category."com.kemalabdic".level=WARN
